export class TimeMapClass {
  id: string = ''
  title: string = ''
  imgSrc: string = ''
  tag: string = ''
  creator: string = ''
  time: string = ''
  brief: string = ''

  constructor(id: string, title: string, imgSrc: string, tag: string, creator: string, time: string, brief: string) {
    id = this.id
    title = this.title
    imgSrc = this.imgSrc
    tag = this.tag
    creator = this.creator
    time = this.time
    brief = this.brief
  }

}