import { ListPage } from 'list'
import { PersonPage } from 'person'
import { IntendPage} from 'intend'
import { BreakpointSystem, BreakpointTypeEnum } from 'utils';


@Entry
@Component
struct Index {
  @State currentIndex: number = 0;
  @StorageProp('currentBreakpoint') currentBreakpoint: string = BreakpointTypeEnum.MD;
  private tabsController: TabsController = new TabsController()
  private breakpointSystem: BreakpointSystem = new BreakpointSystem();

  aboutToAppear() {
    this.breakpointSystem.register();
  }

  aboutToDisappear() {
    this.breakpointSystem.unregister();
  }

  @Builder
  tabBarBuilder(title: string, targetIndex: number, selectedIcon: Resource, unselectIcon: Resource){
    Column(){
      Image(this.currentIndex === targetIndex ? selectedIcon: unselectIcon)
        .width(24)
        .height(24)
      Text(title)
        .fontFamily('HarmonyHeiTi-Medium')
        .fontSize(10)
        .fontColor(this.currentIndex === targetIndex ? '#0A59F7' : 'rgba(0,0,0,0,60)')
        .textAlign(TextAlign.Center)
        .lineHeight(14)
        .fontWeight(500)
    }
    .width('100%')
    .height('100%')
    .justifyContent(FlexAlign.Center)
    .alignItems(HorizontalAlign.Center)
    .onClick(() => {
      this.currentIndex = targetIndex
      this.tabsController.changeIndex(targetIndex)
    })
  }

  build() {
    Tabs({
      barPosition: this.currentBreakpoint === BreakpointTypeEnum.LG ?
      BarPosition.Start :
      BarPosition.End,
      controller: this.tabsController
    }) {
      TabContent() {
        ListPage()
      }
      .tabBar(this.tabBarBuilder('列表', 0, $r('app.media.ic_01_on'), $r('app.media.ic_01_off')))

      TabContent() {
        IntendPage()
      }
      .tabBar(this.tabBarBuilder('一计', 1, $r('app.media.ic_02_on'), $r('app.media.ic_02_off')))

      TabContent() {
        PersonPage()
      }
      .tabBar(this.tabBarBuilder('个人', 2, $r('app.media.ic_03_on'), $r('app.media.ic_03_off')))
    }
    .vertical(this.currentBreakpoint === BreakpointTypeEnum.LG ? true : false)
    .divider({
      strokeWidth: 0.5,
      color: '#0D182431'
    })
    .scrollable(false)
    .backgroundColor('#F1F3F5')
    .padding({ top: 36, bottom: 28 })
    .expandSafeArea([SafeAreaType.SYSTEM], [SafeAreaEdge.TOP, SafeAreaEdge.BOTTOM])
  }
}